### ISSUE TITLE
Data loss with nuget package versions 2.1.4 through to 2.1.9

### ISSUE THREAD

**Issue by jiggyswift** [IEvangelist/azure-cosmos-dotnet-repository#52]
Sorry for being melodramatic, but this bug is critical enough and will definitely cause data loss in production.  It is likely people will review this when trying to resolve.

Temporary resolution: Downgrade to nuget package version 2.1.3 until this issue has been resolved.  I have verified version 2.1.3 has the correct behaviour.

With versions 2.1.4 through to 2.1.9, if you are storing multiple types within a single container in cosmos (which would be the default for most users), you will quickly corrupt your database.  In summary, the codebase attempts to add an additional where clause to the predicate you supply to GetAsync, but the logic is not correct.  

If you want a work around this bug and use more recent nuget package versions, you MUST include your own type filter within the predicate, for example if your type is MyName, you would have written this:
```
db.GetAsync(i => i.FirstName == "Fred")
```
If you use nuget package 2.1.4 to 2.1.9 you MUST include your own type filter in your supplied predicate like this:
```
db.GetAsync(i => i.FirstName == "Fred" && i.Type == nameof(MyType))
```
If you do not do this on later package version, you will end up corrupting your data.

**Comment by IEvangelist** [comment]
Hi @jiggyswift,

Oh my, I was unware of this issue. I'm going to try to reproduce it and see what I can figure out. We've had the concept of the `Type` discriminator in place for a while now - and I've been using this in production, and I've not see this behavior.

1. What were your settings before, did anything there change - specifically the `ContainerPerItemType`?
1. Did the shape of your object change?

As for the data corruption statement, that's a scary claim - I hope you're wrong. But let's work together to verify that. If an item was created in an earlier version, it wouldn't have a `Type` discriminator on it. And reads would be fine reading without that, as the `.IsDefined` lets us know if it has one or not. That's an OR on the type name check. After it once the item is read out and updated, in later versions it will add that property. So, it works as expected. I'm still looking, but if you have an exact example of how to reproduce this - it would be really helpful.

**Comment by jiggyswift** [comment]
Hi David,

The data loss just flows on from it not discriminating on the Type.  Just to be clear: to get this working (and recommend version 2.1.3) I started with 2.1.9 in my .NET 5 project, then just kept rolling back to your earlier nuget package versions, one at a time.  When I got to 2.1.3 it started working correctly.  So the only change to my project to get it working was rolling back to 2.1.3 (all nuget package versions since I have tested and do NOT work - i.e have this issue).

One other thought: Has there been any change in deserialization used under the covers where the lowercase "type" in the JSON could be causing an issue.  If so, it might depend on a project's JSON deserialization settings (I am just using defaults and have not changed anything).  I do see my fields are being serialized in upper case, but your base Item classes "Id" and "Type" fields are being serialized as "id" and "type" - not sure if a change in default JSON deserialization settings would cause an issue (and this might be a red herring).

My settings:
```
"RepositoryOptions": {
    "CosmosConnectionString": "xxxx",
    "DatabaseId": "am",
    "ContainerId": "db",
    "OptimizeBandwidth": true,
    "ContainerPerItemType": false
  }
```

Here is an example of how an object appears when serialized into Cosmos:
```
{
    "Account": "dav",
    "Active": true,
    "Created": "2021-06-15T15:05:25.6102613Z",
    "id": "3b2ebdfb-2850-4e64-a233-6ea312e7faea",
    "type": "Person",
    "_rid": "SjxvAI5RfWQrAAAAAAAAAA==",
    "_self": "dbs/SjxvAA==/colls/SjxvAI5RfWQ=/docs/SjxvAI5RfWQrAAAAAAAAAA==/",
    "_etag": "\"10010bed-0000-1b00-0000-60c8c1c30000\"",
    "_attachments": "attachments/",
    "_ts": 1623769539
}
```

If you cannot work it out from this, I will have more time next week, and will put together a stand alone .NET 5 console project demonstrating this.

**Comment by jiggyswift** [comment]
David, not sure if this helps, but in Azure if I open up the Cosmos instance and type a query into the SQL API, I get these results:

This returns nothing (Type is in uppercase)
select * from c where c.Type = 'Person'

This returns the current list of objects (type is in lowercase)
select * from c where c.type = 'Person'

So it would appear the Cosmos SQL API cares about the casing of the JSON.  If I took a guess, it would be that your cosmos filter is case sensitive (at least the way the query is being sent into the Cosmos SQL API)?  You will need to make sure both "type" and "Type" are checked, when using the Cosmos SQL APIs.  Does that help with the diagnosis?  Possibly something changed between your 2.1.3 package and later packages that has made this a case sensitive filter?

**Comment by IEvangelist** [comment]
I didn't think that things were case sensitive - I'm really curious now as that does sound like a difference in behavior as it relates to serialization. I'll try to look more closely tonight. Thanks for the follow up on this.

**Comment by jrwmacedo** [comment]
Hello David, I was able to reproduce this issue as well. The issue just affects this overload of the GetAsync method.
`    ValueTask<IEnumerable<TItem>> GetAsync(
      Expression<Func<TItem, bool>> predicate,
      CancellationToken cancellationToken = default (CancellationToken));`

![image](https://user-images.githubusercontent.com/12876899/125843102-f7ab4a61-33bb-49cf-b68f-0a188017ba14.png)

The query generated in line 97 from the DefaultRepository.cs is not building the Type word properly.
See my example:

`SELECT VALUE root FROM root WHERE ((root["sellerId"] = "4a6448f9-ee10-4831-a371-afcd0b2bc911") AND ((NOT IS_DEFINED(root["Type"])) OR (root["Type"] = "SellerShopProfileDto")))`
Due to the Type word is in uppercase, the condition "IS_DEFINED equal to False" is True so, the query is returning all the type into the container.
![image](https://user-images.githubusercontent.com/12876899/125847294-57d61bda-aab1-4a96-8745-ebcd4ef8c485.png)

if we change to that, the correct type is returned.
`SELECT VALUE root FROM root WHERE ((root["sellerId"] = "4a6448f9-ee10-4831-a371-afcd0b2bc911") AND ((NOT IS_DEFINED(root["type"])) OR (root["type"] = "SellerShopProfileDto")))`

![image](https://user-images.githubusercontent.com/12876899/125847071-4f01fee1-52b3-43cf-9f4b-7aecd6b789f6.png)

Let me know if you need some help.

Cheers!

**Comment by amdav** [comment]
The original poster (David/jiggyswift) here.  I looked at my code again and confirm this completely explains the issue.

At noted, this impacts all versions after 2.1.3.  I am still running on 2.1.3, which does not have this bug, as it was causing my production data to be deleted because all items (or any type) were being loaded (due to the issue with the capitalization of 'type' versus 'Type'), and then when saved wrote the incorrect object type back into the database (deleting some important data).

With any fix, we need to make sure either capitalization will work "Type" or "type".

**Comment by jrwmacedo** [comment]
Hello @IEvangelist , good morning.
I already have a fix for that and the PR is created, however, I need permission to push it.
Could you give me that?

Many thanks,
Junior

**Comment by IEvangelist** [comment]
Closing this as it has been fixed:
https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/Item.cs#L47

**Comment by sven5** [comment]
@IEvangelist Sorry for interruption. I still have the issue with `Type` 
my query:
`{"query":"SELECT VALUE root FROM root WHERE ((root[\"categoryId\"] = \"something\") AND ((NOT IS_DEFINED(root[\"Type\"])) OR (root[\"Type\"] = \"Product\")))"}`

and the item looks like:

```
    "id": "ec4f8448-7008-402a-8cd4-500b8cde49e0",
    "type": "Product",
    "_rid": "gIowAPNwNOkEAAAAAAAAAA==",
```

the query is not working correctly.
